name: Build course

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: shopjupyterhubacr.azurecr.io/shop/linux/python3.10/vlab:latest
      options: --user root -e GRANT_SUDO=yes
      credentials:
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
    steps:
      - uses: actions/checkout@v3
      - name: Build book
        run: jupyter book build ./introduction/
      - name: Modify html
        run: |
          python -c 'from scripts import insert_line_in_all_html
          insert_line_in_all_html("./introduction/_build/html/")'
      - name: Upload to portal
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: shop.sintef.energy
          username: ${{ secrets.SHOP_PORTAL_FTP_USERNAME }}
          password: ${{ secrets.SHOP_PORTAL_FTP_PASSWORD }}
          local-dir: ./introduction/_build/html/
          server-dir: doc/course/introduction/html/
